[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
ciphers = { path = "../ciphers" }

actix-cors = "0.6.4"
actix-web = "4.3.1"
serde = { version = "1.0.178", features = ["derive"] }
env_logger = "0.10.0"