[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
ciphers = { path = "../ciphers" }

actix-web = "4.3.1"
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"
